import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import "dotenv/config";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter } as ConstructorParameters<typeof PrismaClient>[0]);

async function main() {
  console.log("Seeding new subjects...");

  // ============================================================
  // 簿記3級
  // ============================================================
  const bookkeeping3Questions = [
    // Section A: 仕訳と帳簿
    {
      subject: "bookkeeping3",
      topic: "仕訳と帳簿",
      content: "商品¥50,000を現金で仕入れた。正しい仕訳はどれか。",
      optionA: "（借）仕入 50,000 ／ （貸）現金 50,000",
      optionB: "（借）現金 50,000 ／ （貸）仕入 50,000",
      optionC: "（借）商品 50,000 ／ （貸）現金 50,000",
      optionD: "（借）買掛金 50,000 ／ （貸）現金 50,000",
      correctAnswer: "A",
      explanation: "商品を現金で仕入れた場合、費用（仕入）の増加を借方に、資産（現金）の減少を貸方に記入します。",
      difficulty: "easy",
      language: "ja",
    },
    {
      subject: "bookkeeping3",
      topic: "仕訳と帳簿",
      content: "商品¥80,000を掛けで売り上げた（原価¥50,000）。正しい仕訳はどれか。",
      optionA: "（借）売掛金 80,000 ／ （貸）売上 80,000",
      optionB: "（借）現金 80,000 ／ （貸）売上 80,000",
      optionC: "（借）売掛金 80,000 ／ （貸）商品 80,000",
      optionD: "（借）売上 80,000 ／ （貸）売掛金 80,000",
      correctAnswer: "A",
      explanation: "掛け売上の場合、資産（売掛金）の増加を借方に、収益（売上）の発生を貸方に記入します。原価の仕訳は三分法では別途行いません。",
      difficulty: "easy",
      language: "ja",
    },
    {
      subject: "bookkeeping3",
      topic: "仕訳と帳簿",
      content: "買掛金¥30,000を現金で支払った。正しい仕訳はどれか。",
      optionA: "（借）買掛金 30,000 ／ （貸）現金 30,000",
      optionB: "（借）現金 30,000 ／ （貸）買掛金 30,000",
      optionC: "（借）仕入 30,000 ／ （貸）現金 30,000",
      optionD: "（借）支払手形 30,000 ／ （貸）現金 30,000",
      correctAnswer: "A",
      explanation: "買掛金（負債）の減少は借方に記入します。現金（資産）の減少は貸方に記入します。",
      difficulty: "easy",
      language: "ja",
    },
    {
      subject: "bookkeeping3",
      topic: "仕訳と帳簿",
      content: "給料¥200,000を現金で支払った。正しい仕訳はどれか。",
      optionA: "（借）給料 200,000 ／ （貸）現金 200,000",
      optionB: "（借）現金 200,000 ／ （貸）給料 200,000",
      optionC: "（借）給料 200,000 ／ （貸）未払金 200,000",
      optionD: "（借）人件費 200,000 ／ （貸）現金 200,000",
      correctAnswer: "A",
      explanation: "給料（費用）の発生は借方に記入し、現金（資産）の減少は貸方に記入します。",
      difficulty: "easy",
      language: "ja",
    },
    {
      subject: "bookkeeping3",
      topic: "仕訳と帳簿",
      content: "現金出納帳の「借方」に記入するのはどの取引か。",
      optionA: "現金を受け取った取引",
      optionB: "現金を支払った取引",
      optionC: "商品を仕入れた取引",
      optionD: "売掛金が発生した取引",
      correctAnswer: "A",
      explanation: "現金出納帳の借方（左側）には現金の受取（増加）を記入します。貸方（右側）には現金の支払（減少）を記入します。",
      difficulty: "easy",
      language: "ja",
    },
    {
      subject: "bookkeeping3",
      topic: "仕訳と帳簿",
      content: "総勘定元帳において、各勘定の残高を求める際の基本的な考え方として正しいものはどれか。",
      optionA: "借方合計と貸方合計の差額が残高となる",
      optionB: "借方合計と貸方合計の合計が残高となる",
      optionC: "最後に記入した金額が残高となる",
      optionD: "取引件数を掛けた金額が残高となる",
      correctAnswer: "A",
      explanation: "勘定残高は「借方合計 - 貸方合計」（借方残高の場合）または「貸方合計 - 借方合計」（貸方残高の場合）で求めます。",
      difficulty: "medium",
      language: "ja",
    },
    // Section B: 決算整理
    {
      subject: "bookkeeping3",
      topic: "決算整理",
      content: "期末に売掛金¥100,000に対し2%の貸倒引当金を設定する（貸倒引当金残高¥0）。正しい仕訳はどれか。",
      optionA: "（借）貸倒引当金繰入 2,000 ／ （貸）貸倒引当金 2,000",
      optionB: "（借）貸倒引当金 2,000 ／ （貸）売掛金 2,000",
      optionC: "（借）売掛金 2,000 ／ （貸）貸倒引当金 2,000",
      optionD: "（借）貸倒損失 2,000 ／ （貸）売掛金 2,000",
      correctAnswer: "A",
      explanation: "貸倒引当金の設定は「貸倒引当金繰入（費用）」の増加を借方に、「貸倒引当金（資産のマイナス）」の増加を貸方に記入します。",
      difficulty: "medium",
      language: "ja",
    },
    {
      subject: "bookkeeping3",
      topic: "決算整理",
      content: "備品¥300,000（耐用年数5年、残存価値ゼロ）を定額法で減価償却する。1年分の減価償却費はいくらか。",
      optionA: "¥60,000",
      optionB: "¥30,000",
      optionC: "¥150,000",
      optionD: "¥75,000",
      correctAnswer: "A",
      explanation: "定額法の計算式：取得原価 ÷ 耐用年数 = ¥300,000 ÷ 5年 = ¥60,000",
      difficulty: "easy",
      language: "ja",
    },
    {
      subject: "bookkeeping3",
      topic: "決算整理",
      content: "期末に消耗品の未使用残高¥5,000が判明した（期中に消耗品費¥20,000を計上済み）。決算整理仕訳として正しいものはどれか。",
      optionA: "（借）消耗品 5,000 ／ （貸）消耗品費 5,000",
      optionB: "（借）消耗品費 5,000 ／ （貸）消耗品 5,000",
      optionC: "（借）消耗品費 5,000 ／ （貸）現金 5,000",
      optionD: "（借）消耗品 20,000 ／ （貸）消耗品費 20,000",
      correctAnswer: "A",
      explanation: "未使用の消耗品を資産（消耗品）に振り替えるため、消耗品（資産）の増加を借方に、消耗品費（費用）の減少を貸方に記入します。",
      difficulty: "medium",
      language: "ja",
    },
    {
      subject: "bookkeeping3",
      topic: "決算整理",
      content: "期末に保険料の前払分¥12,000が判明した。決算整理仕訳として正しいものはどれか。",
      optionA: "（借）前払保険料 12,000 ／ （貸）保険料 12,000",
      optionB: "（借）保険料 12,000 ／ （貸）前払保険料 12,000",
      optionC: "（借）未払保険料 12,000 ／ （貸）保険料 12,000",
      optionD: "（借）保険料 12,000 ／ （貸）現金 12,000",
      correctAnswer: "A",
      explanation: "前払費用は次期以降の費用を当期に支払ったものです。資産（前払保険料）の増加を借方に、費用（保険料）の減少を貸方に記入します。",
      difficulty: "medium",
      language: "ja",
    },
    {
      subject: "bookkeeping3",
      topic: "決算整理",
      content: "期末に受取地代の未収分¥8,000が判明した。決算整理仕訳として正しいものはどれか。",
      optionA: "（借）未収地代 8,000 ／ （貸）受取地代 8,000",
      optionB: "（借）受取地代 8,000 ／ （貸）未収地代 8,000",
      optionC: "（借）未収地代 8,000 ／ （貸）現金 8,000",
      optionD: "（借）前受地代 8,000 ／ （貸）受取地代 8,000",
      correctAnswer: "A",
      explanation: "未収収益は当期に発生したが未収の収益です。資産（未収地代）の増加を借方に、収益（受取地代）の増加を貸方に記入します。",
      difficulty: "medium",
      language: "ja",
    },
    // Section C: 財務諸表
    {
      subject: "bookkeeping3",
      topic: "財務諸表",
      content: "貸借対照表において、流動資産に分類されるものはどれか。",
      optionA: "売掛金",
      optionB: "建物",
      optionC: "資本金",
      optionD: "長期借入金",
      correctAnswer: "A",
      explanation: "売掛金は1年以内に回収が見込まれる流動資産です。建物は固定資産、資本金は純資産、長期借入金は固定負債に分類されます。",
      difficulty: "easy",
      language: "ja",
    },
    {
      subject: "bookkeeping3",
      topic: "財務諸表",
      content: "損益計算書の「売上総利益」の計算式として正しいものはどれか。",
      optionA: "売上高 − 売上原価",
      optionB: "売上高 − 販売費及び一般管理費",
      optionC: "売上高 − 売上原価 − 販売費及び一般管理費",
      optionD: "売上高 + 営業外収益",
      correctAnswer: "A",
      explanation: "売上総利益 = 売上高 − 売上原価 です。ここから販売費及び一般管理費を差し引いたものが営業利益になります。",
      difficulty: "easy",
      language: "ja",
    },
    {
      subject: "bookkeeping3",
      topic: "財務諸表",
      content: "貸借対照表の等式（バランスシート等式）として正しいものはどれか。",
      optionA: "資産 = 負債 + 純資産",
      optionB: "資産 = 負債 − 純資産",
      optionC: "資産 + 負債 = 純資産",
      optionD: "純資産 = 資産 − 収益",
      correctAnswer: "A",
      explanation: "貸借対照表の基本等式は「資産 = 負債 + 純資産」です。左側（借方）に資産、右側（貸方）に負債と純資産が記載されます。",
      difficulty: "easy",
      language: "ja",
    },
    {
      subject: "bookkeeping3",
      topic: "財務諸表",
      content: "期首資本¥500,000、期末資本¥650,000、追加出資なし・配当なしの場合、当期純利益はいくらか。",
      optionA: "¥150,000",
      optionB: "¥1,150,000",
      optionC: "¥500,000",
      optionD: "¥650,000",
      correctAnswer: "A",
      explanation: "当期純利益 = 期末資本 − 期首資本 = ¥650,000 − ¥500,000 = ¥150,000（追加出資・配当がない場合）",
      difficulty: "medium",
      language: "ja",
    },
    {
      subject: "bookkeeping3",
      topic: "財務諸表",
      content: "次のうち、損益計算書に記載されるものはどれか。",
      optionA: "減価償却費",
      optionB: "減価償却累計額",
      optionC: "繰越利益剰余金",
      optionD: "買掛金",
      correctAnswer: "A",
      explanation: "減価償却費は費用であり損益計算書に記載されます。減価償却累計額は貸借対照表（資産のマイナス）、繰越利益剰余金と買掛金は貸借対照表に記載されます。",
      difficulty: "medium",
      language: "ja",
    },
    // Section D: 手形・その他取引
    {
      subject: "bookkeeping3",
      topic: "手形・その他取引",
      content: "約束手形¥50,000を受け取った。正しい仕訳はどれか。",
      optionA: "（借）受取手形 50,000 ／ （貸）売掛金 50,000",
      optionB: "（借）売掛金 50,000 ／ （貸）受取手形 50,000",
      optionC: "（借）支払手形 50,000 ／ （貸）現金 50,000",
      optionD: "（借）受取手形 50,000 ／ （貸）現金 50,000",
      correctAnswer: "A",
      explanation: "売掛金を約束手形で回収した場合、受取手形（資産）の増加を借方に、売掛金（資産）の減少を貸方に記入します。",
      difficulty: "medium",
      language: "ja",
    },
    {
      subject: "bookkeeping3",
      topic: "手形・その他取引",
      content: "商品¥100,000を仕入れ、代金として約束手形を振り出した。正しい仕訳はどれか。",
      optionA: "（借）仕入 100,000 ／ （貸）支払手形 100,000",
      optionB: "（借）仕入 100,000 ／ （貸）受取手形 100,000",
      optionC: "（借）支払手形 100,000 ／ （貸）仕入 100,000",
      optionD: "（借）仕入 100,000 ／ （貸）買掛金 100,000",
      correctAnswer: "A",
      explanation: "手形を振り出して仕入れた場合、仕入（費用）の増加を借方に、支払手形（負債）の増加を貸方に記入します。",
      difficulty: "medium",
      language: "ja",
    },
    {
      subject: "bookkeeping3",
      topic: "手形・その他取引",
      content: "固定資産（備品¥200,000、帳簿価額¥80,000）を¥100,000で売却し、代金は現金で受け取った。正しい仕訳はどれか。",
      optionA: "（借）現金 100,000・減価償却累計額 120,000 ／ （貸）備品 200,000・固定資産売却益 20,000",
      optionB: "（借）現金 100,000 ／ （貸）備品 100,000",
      optionC: "（借）現金 100,000 ／ （貸）備品 80,000・固定資産売却益 20,000",
      optionD: "（借）現金 200,000 ／ （貸）備品 200,000",
      correctAnswer: "A",
      explanation: "固定資産売却益 = 売却価格 − 帳簿価額 = ¥100,000 − ¥80,000 = ¥20,000。備品の取得原価と減価償却累計額の両方を消去します。",
      difficulty: "hard",
      language: "ja",
    },
    {
      subject: "bookkeeping3",
      topic: "手形・その他取引",
      content: "電子記録債権とは何か。",
      optionA: "電子債権記録機関に記録することで発生する金銭債権",
      optionB: "インターネットバンキングで振り込まれた債権",
      optionC: "クレジットカードによる売掛金",
      optionD: "電子メールで通知された債権",
      correctAnswer: "A",
      explanation: "電子記録債権は、電子債権記録機関（でんさいネット等）への電子記録によって発生・譲渡される金銭債権です。従来の手形や売掛金に代わる決済手段です。",
      difficulty: "medium",
      language: "ja",
    },
    {
      subject: "bookkeeping3",
      topic: "手形・その他取引",
      content: "小口現金制度において、用度係から報告を受け、小切手を補給した。この仕訳として正しいものはどれか。",
      optionA: "（借）交通費・消耗品費等 ／ （貸）当座預金",
      optionB: "（借）小口現金 ／ （貸）当座預金",
      optionC: "（借）当座預金 ／ （貸）小口現金",
      optionD: "（借）現金 ／ （貸）小口現金",
      correctAnswer: "A",
      explanation: "定額補給制度では、報告を受けた時点で各費用を計上し、補給額と同額の小切手（当座預金）を振り出します。小口現金勘定の残高は変わりません。",
      difficulty: "hard",
      language: "ja",
    },
  ];

  // ============================================================
  // 簿記2級
  // ============================================================
  const bookkeeping2Questions = [
    // Section A: 工業簿記・原価計算
    {
      subject: "bookkeeping2",
      topic: "工業簿記・原価計算",
      content: "製品原価の構成として正しいものはどれか。",
      optionA: "直接材料費＋直接労務費＋製造間接費",
      optionB: "直接材料費＋直接労務費＋販売費",
      optionC: "直接材料費＋製造間接費＋一般管理費",
      optionD: "変動費＋固定費＋販売費",
      correctAnswer: "A",
      explanation: "製品原価（製造原価）は「直接材料費＋直接労務費＋製造間接費」で構成されます。販売費や一般管理費は期間原価（製品原価に含まれない）です。",
      difficulty: "easy",
      language: "ja",
    },
    {
      subject: "bookkeeping2",
      topic: "工業簿記・原価計算",
      content: "材料¥500,000を掛けで購入し、引取運賃¥20,000を現金で支払った。材料の取得原価はいくらか。",
      optionA: "¥520,000",
      optionB: "¥500,000",
      optionC: "¥480,000",
      optionD: "¥20,000",
      correctAnswer: "A",
      explanation: "材料の取得原価には購入代価に加え、引取運賃などの付随費用も含まれます。¥500,000＋¥20,000＝¥520,000",
      difficulty: "easy",
      language: "ja",
    },
    {
      subject: "bookkeeping2",
      topic: "工業簿記・原価計算",
      content: "製造間接費の配賦率を求める計算式として正しいものはどれか。",
      optionA: "予定製造間接費 ÷ 予定配賦基準量",
      optionB: "実際製造間接費 ÷ 実際配賦基準量",
      optionC: "予定配賦基準量 ÷ 予定製造間接費",
      optionD: "実際製造間接費 ÷ 予定配賦基準量",
      correctAnswer: "A",
      explanation: "予定配賦率＝予定製造間接費÷予定配賦基準量（例：予定直接作業時間）。これを用いて各製品への製造間接費を予定配賦します。",
      difficulty: "medium",
      language: "ja",
    },
    {
      subject: "bookkeeping2",
      topic: "工業簿記・原価計算",
      content: "損益分岐点売上高を求める計算式として正しいものはどれか。",
      optionA: "固定費 ÷ 限界利益率",
      optionB: "固定費 × 限界利益率",
      optionC: "変動費 ÷ 限界利益率",
      optionD: "固定費 ÷ 変動費率",
      correctAnswer: "A",
      explanation: "損益分岐点売上高 = 固定費 ÷ 限界利益率（限界利益率 = 1 − 変動費率）。この売上高では利益がゼロになります。",
      difficulty: "medium",
      language: "ja",
    },
    {
      subject: "bookkeeping2",
      topic: "工業簿記・原価計算",
      content: "総合原価計算において、月末仕掛品の評価に用いる「平均法」の説明として正しいものはどれか。",
      optionA: "月初仕掛品と当月投入の合算コストを完成品換算量で平均する方法",
      optionB: "先に投入したものを先に完成させたとみなす方法",
      optionC: "後から投入したものを先に完成させたとみなす方法",
      optionD: "月末仕掛品を無視して全額を完成品に負担させる方法",
      correctAnswer: "A",
      explanation: "平均法は月初仕掛品原価と当月製造費用の合計を、完成品換算量（完成品量＋月末仕掛品換算量）で割って平均単価を算定する方法です。",
      difficulty: "hard",
      language: "ja",
    },
    {
      subject: "bookkeeping2",
      topic: "工業簿記・原価計算",
      content: "標準原価計算における「直接材料費差異」を分解したものはどれか。",
      optionA: "価格差異と数量差異",
      optionB: "賃率差異と作業時間差異",
      optionC: "予算差異と操業度差異",
      optionD: "固定費差異と変動費差異",
      correctAnswer: "A",
      explanation: "直接材料費差異は「価格差異（実際単価と標準単価の差）」と「数量差異（実際消費量と標準消費量の差）」に分析されます。",
      difficulty: "hard",
      language: "ja",
    },
    // Section B: 株式会社の会計
    {
      subject: "bookkeeping2",
      topic: "株式会社の会計",
      content: "株式会社が株式¥1,000,000（1株¥1,000×1,000株）を発行した。全額を資本金に計上する場合の仕訳はどれか。",
      optionA: "（借）当座預金 1,000,000 ／ （貸）資本金 1,000,000",
      optionB: "（借）資本金 1,000,000 ／ （貸）当座預金 1,000,000",
      optionC: "（借）当座預金 1,000,000 ／ （貸）資本準備金 1,000,000",
      optionD: "（借）株式 1,000,000 ／ （貸）資本金 1,000,000",
      correctAnswer: "A",
      explanation: "株式発行時、払込金を当座預金（資産）の増加として借方に、資本金（純資産）の増加として貸方に記入します。",
      difficulty: "easy",
      language: "ja",
    },
    {
      subject: "bookkeeping2",
      topic: "株式会社の会計",
      content: "株主配当金¥300,000を繰越利益剰余金から支払うことを決議した。仕訳として正しいものはどれか。",
      optionA: "（借）繰越利益剰余金 300,000 ／ （貸）未払配当金 300,000",
      optionB: "（借）未払配当金 300,000 ／ （貸）繰越利益剰余金 300,000",
      optionC: "（借）繰越利益剰余金 300,000 ／ （貸）現金 300,000",
      optionD: "（借）配当金 300,000 ／ （貸）当座預金 300,000",
      correctAnswer: "A",
      explanation: "配当決議時は、繰越利益剰余金（純資産）の減少を借方に、未払配当金（負債）の発生を貸方に記入します。支払時に未払配当金を取り崩します。",
      difficulty: "medium",
      language: "ja",
    },
    {
      subject: "bookkeeping2",
      topic: "株式会社の会計",
      content: "法定準備金の積み立てに関して、会社法で定められた利益準備金の積立限度額として正しいものはどれか。",
      optionA: "資本金の4分の1",
      optionB: "資本金の2分の1",
      optionC: "資本金の全額",
      optionD: "配当金の10分の1",
      correctAnswer: "A",
      explanation: "会社法では、利益準備金（および資本準備金の合計）が資本金の1/4に達するまで、配当時に剰余金の1/10を積み立てることが義務付けられています。",
      difficulty: "hard",
      language: "ja",
    },
    {
      subject: "bookkeeping2",
      topic: "株式会社の会計",
      content: "自己株式を取得した場合の仕訳として正しいものはどれか。",
      optionA: "（借）自己株式 ／ （貸）現金等",
      optionB: "（借）現金等 ／ （貸）自己株式",
      optionC: "（借）資本金 ／ （貸）現金等",
      optionD: "（借）有価証券 ／ （貸）現金等",
      correctAnswer: "A",
      explanation: "自己株式は純資産のマイナス項目として処理します。取得時は自己株式（純資産のマイナス）の増加を借方に、支払代金を貸方に記入します。",
      difficulty: "medium",
      language: "ja",
    },
    // Section C: 特殊商品売買
    {
      subject: "bookkeeping2",
      topic: "特殊商品売買",
      content: "委託販売において、委託者（荷主）が積送した商品の仕訳として正しいものはどれか。",
      optionA: "（借）積送品 ／ （貸）仕入（または商品）",
      optionB: "（借）仕入 ／ （貸）積送品",
      optionC: "（借）売上 ／ （貸）積送品",
      optionD: "（借）積送品 ／ （貸）売上",
      correctAnswer: "A",
      explanation: "委託販売では、商品を積送した時点で商品（仕入）から積送品勘定に振り替えます。売上計上は受託者から仕切精算書を受け取った時です。",
      difficulty: "medium",
      language: "ja",
    },
    {
      subject: "bookkeeping2",
      topic: "特殊商品売買",
      content: "割賦販売（回収基準）において、販売代金を回収した時点で売上計上する方法での仕訳として正しいものはどれか。",
      optionA: "代金回収時に売上を計上する",
      optionB: "商品引渡時に全額売上を計上する",
      optionC: "割賦金の最終回収時にまとめて計上する",
      optionD: "売買契約締結時に計上する",
      correctAnswer: "A",
      explanation: "割賦販売の回収基準では、割賦金を実際に回収した時点で売上を計上します（現行では原則として引渡基準を使用）。",
      difficulty: "hard",
      language: "ja",
    },
    {
      subject: "bookkeeping2",
      topic: "特殊商品売買",
      content: "試用販売において、得意先が試用中の商品はどの勘定で処理されるか。",
      optionA: "試用品（または積送品）",
      optionB: "売掛金",
      optionC: "商品",
      optionD: "前払金",
      correctAnswer: "A",
      explanation: "試用販売では、商品を得意先に送付した時点で「試用品」勘定に振り替えます。得意先が購入の意思表示をした時点で売上を計上します。",
      difficulty: "medium",
      language: "ja",
    },
    // Section D: 本支店会計
    {
      subject: "bookkeeping2",
      topic: "本支店会計",
      content: "本支店会計において、本店が支店へ¥200,000を送金した場合の本店側の仕訳はどれか。",
      optionA: "（借）支店 200,000 ／ （貸）現金 200,000",
      optionB: "（借）現金 200,000 ／ （貸）支店 200,000",
      optionC: "（借）本店 200,000 ／ （貸）現金 200,000",
      optionD: "（借）支店 200,000 ／ （貸）本店 200,000",
      correctAnswer: "A",
      explanation: "本店が支店へ送金した場合、本店は支店勘定（資産）を借方に、現金を貸方に記入します。支店側では現金を借方、本店勘定を貸方に記入します。",
      difficulty: "medium",
      language: "ja",
    },
    {
      subject: "bookkeeping2",
      topic: "本支店会計",
      content: "合併財務諸表を作成する際、最初に行う内部取引の消去仕訳として正しいものはどれか。",
      optionA: "本店勘定と支店勘定を相殺消去する",
      optionB: "売上と仕入を加算する",
      optionC: "本店の利益を支店に配分する",
      optionD: "支店の固定資産を本店に移転する",
      correctAnswer: "A",
      explanation: "合併財務諸表作成時には、本店の「支店勘定」と支店の「本店勘定」を相殺消去します。また、本支店間の内部取引（売上・仕入等）も消去します。",
      difficulty: "hard",
      language: "ja",
    },
    {
      subject: "bookkeeping2",
      topic: "本支店会計",
      content: "本店が支店に商品を¥150,000で送付した（原価¥120,000）場合、合併損益計算書を作成する際に必要な消去処理はどれか。",
      optionA: "内部振替価格¥150,000の売上と仕入を相殺消去し、未実現利益¥30,000を消去する",
      optionB: "内部振替価格¥150,000の売上と仕入を加算する",
      optionC: "原価¥120,000を消去する",
      optionD: "利益¥30,000を支店の売上に計上する",
      correctAnswer: "A",
      explanation: "合併財務諸表では、本支店間の内部取引（売上¥150,000と仕入¥150,000）を相殺消去し、さらに未販売商品に含まれる未実現内部利益を消去します。",
      difficulty: "hard",
      language: "ja",
    },
  ];

  // ============================================================
  // TOEIC 600点
  // ============================================================
  const toeic600Questions = [
    // Section A: 語彙・文法
    {
      subject: "toeic600",
      topic: "語彙・文法",
      content: "空欄に入る最も適切な語を選んでください。\n\nThe manager asked all employees to ______ the new safety regulations.",
      optionA: "comply with",
      optionB: "comply to",
      optionC: "comply at",
      optionD: "comply for",
      correctAnswer: "A",
      explanation: "「comply with ～」で「〜に従う/〜を遵守する」という意味の重要イディオムです。前置詞は必ず with を使います。",
      difficulty: "easy",
      language: "ja",
    },
    {
      subject: "toeic600",
      topic: "語彙・文法",
      content: "空欄に入る最も適切な語を選んでください。\n\nThe conference will be held ______ Friday afternoon.",
      optionA: "on",
      optionB: "in",
      optionC: "at",
      optionD: "by",
      correctAnswer: "A",
      explanation: "曜日・特定の日には前置詞 on を使います（on Friday / on Monday morning）。in は月・年・季節、at は時刻に使います。",
      difficulty: "easy",
      language: "ja",
    },
    {
      subject: "toeic600",
      topic: "語彙・文法",
      content: "空欄に入る最も適切な語を選んでください。\n\nThe project was ______ completed before the deadline.",
      optionA: "successfully",
      optionB: "success",
      optionC: "successful",
      optionD: "succeed",
      correctAnswer: "A",
      explanation: "動詞（completed）を修飾するので副詞 successfully が正解です。success（名詞）・successful（形容詞）・succeed（動詞）は品詞が異なります。",
      difficulty: "easy",
      language: "ja",
    },
    {
      subject: "toeic600",
      topic: "語彙・文法",
      content: "空欄に入る最も適切な語を選んでください。\n\nCustomers are ______ to contact our support team if they have any questions.",
      optionA: "encouraged",
      optionB: "discouraging",
      optionC: "encouragement",
      optionD: "encourage",
      correctAnswer: "A",
      explanation: "「be encouraged to do」で「〜するよう促される/勧められる」という受動態の表現です。主語 Customers が促される側なので受動態になります。",
      difficulty: "medium",
      language: "ja",
    },
    {
      subject: "toeic600",
      topic: "語彙・文法",
      content: "次の文中の下線部の意味として最も適切なものを選んでください。\n\nThe company will __postpone__ the product launch until further notice.",
      optionA: "延期する",
      optionB: "促進する",
      optionC: "取り消す",
      optionD: "発表する",
      correctAnswer: "A",
      explanation: "postpone は「延期する」という意味の動詞です。TOEIC頻出単語で、delay と同義です。",
      difficulty: "easy",
      language: "ja",
    },
    {
      subject: "toeic600",
      topic: "語彙・文法",
      content: "空欄に入る最も適切な語を選んでください。\n\nAll staff members ______ attend the mandatory training session next Monday.",
      optionA: "must",
      optionB: "might",
      optionC: "could",
      optionD: "would",
      correctAnswer: "A",
      explanation: "mandatory（必須の）とあるので、義務を表す must が適切です。might/could は可能性、would は意志・仮定を表します。",
      difficulty: "easy",
      language: "ja",
    },
    // Section B: 読解
    {
      subject: "toeic600",
      topic: "読解",
      content: "次のメールを読んで質問に答えてください。\n\nFrom: hr@company.com\nSubject: Annual Performance Review\n\nDear All,\nPlease be advised that annual performance reviews will take place from June 10 to June 20. Each employee will receive a separate email with their scheduled appointment time. If you need to reschedule, contact HR at least 48 hours in advance.\n\nQ: 予約を変更したい場合、何時間前までにHRに連絡する必要がありますか？",
      optionA: "48時間前",
      optionB: "24時間前",
      optionC: "72時間前",
      optionD: "1週間前",
      correctAnswer: "A",
      explanation: "メール中の \"at least 48 hours in advance\" から、少なくとも48時間前に連絡する必要があることがわかります。",
      difficulty: "easy",
      language: "ja",
    },
    {
      subject: "toeic600",
      topic: "読解",
      content: "次のお知らせを読んで質問に答えてください。\n\nNOTICE: The main entrance of Building A will be closed for renovation from July 1 to July 15. During this period, please use the side entrance on Oak Street. We apologize for any inconvenience.\n\nQ: このお知らせの目的は何ですか？",
      optionA: "入口の工事中の代替経路を伝えるため",
      optionB: "ビルの閉鎖を告知するため",
      optionC: "新しいビルの開業を知らせるため",
      optionD: "工事業者を募集するため",
      correctAnswer: "A",
      explanation: "お知らせは「メイン入口が改装工事のため閉鎖中、サイドエントランスを使うよう」案内しています。代替経路の告知が目的です。",
      difficulty: "easy",
      language: "ja",
    },
    {
      subject: "toeic600",
      topic: "読解",
      content: "次の広告を読んで質問に答えてください。\n\nWANTED: Experienced Sales Representative\n・Minimum 3 years of sales experience required\n・Fluent English essential; Japanese a plus\n・Competitive salary and benefits\n・Apply by sending resume to jobs@abc.com by August 31\n\nQ: 日本語のスキルについて、この求人はどのように述べていますか？",
      optionA: "あると望ましいが必須ではない",
      optionB: "必須条件である",
      optionC: "不要である",
      optionD: "上級レベルが必要",
      correctAnswer: "A",
      explanation: "\"Japanese a plus\" は「日本語があればプラスになる（加点要素）」という意味です。essential（必須）ではなく任意の優遇条件です。",
      difficulty: "medium",
      language: "ja",
    },
    {
      subject: "toeic600",
      topic: "読解",
      content: "次の文書を読んで質問に答えてください。\n\nDear Mr. Tanaka,\nThank you for your order (#12345). Your items have been shipped and are expected to arrive within 3–5 business days. You can track your shipment at www.tracking.com using your order number.\n\nQ: Mr. Tanakaはどこで荷物を追跡できますか？",
      optionA: "www.tracking.com",
      optionB: "会社のメインウェブサイト",
      optionC: "電話で問い合わせる",
      optionD: "注文書に記載のURL",
      correctAnswer: "A",
      explanation: "メール中に \"track your shipment at www.tracking.com\" と明記されています。",
      difficulty: "easy",
      language: "ja",
    },
    {
      subject: "toeic600",
      topic: "読解",
      content: "次の文書を読んで質問に答えてください。\n\nRefund Policy: Items may be returned within 30 days of purchase for a full refund, provided they are unused and in their original packaging. Sale items are final sale and cannot be returned.\n\nQ: 返金を受けるための条件として正しいものはどれか。",
      optionA: "未使用かつ元の包装のまま30日以内に返品",
      optionB: "セール品も30日以内であれば返金可能",
      optionC: "使用済みでも元の包装があれば返金可能",
      optionD: "60日以内であれば返金可能",
      correctAnswer: "A",
      explanation: "ポリシーに \"within 30 days\", \"unused\", \"original packaging\" という3条件が示されています。またセール品は返品不可とあります。",
      difficulty: "medium",
      language: "ja",
    },
    // Section C: リスニング
    {
      subject: "toeic600",
      topic: "リスニング",
      content: "【リスニング練習問題】次の会話を読んで質問に答えてください。\n\nWoman: Excuse me, is the post office near here?\nMan: Yes, it's just two blocks down on your left. You can't miss it.\nWoman: Thank you so much!\n\nQ: 男性は郵便局についてどのように説明しましたか？",
      optionA: "2ブロック先の左側にある",
      optionB: "2ブロック先の右側にある",
      optionC: "3ブロック先にある",
      optionD: "この通りにはない",
      correctAnswer: "A",
      explanation: "男性は \"two blocks down on your left\" (2ブロック先の左側) と説明しています。",
      difficulty: "easy",
      language: "ja",
    },
    {
      subject: "toeic600",
      topic: "リスニング",
      content: "【リスニング練習問題】次のアナウンスを読んで質問に答えてください。\n\n\"Attention passengers, Flight 205 to New York has been delayed by approximately one hour due to weather conditions. We apologize for the inconvenience. Updated departure time is now 4:30 PM.\"\n\nQ: フライトが遅延した理由は何ですか？",
      optionA: "天候不良",
      optionB: "技術的な問題",
      optionC: "乗組員の問題",
      optionD: "空港の混雑",
      correctAnswer: "A",
      explanation: "アナウンスで \"due to weather conditions\" (天候状況のため) と明確に理由が述べられています。",
      difficulty: "easy",
      language: "ja",
    },
    {
      subject: "toeic600",
      topic: "リスニング",
      content: "【リスニング練習問題】次の会話を読んで質問に答えてください。\n\nMan: Did you get a chance to review the proposal I sent?\nWoman: Yes, I did. Overall it looks good, but I have a few suggestions for the budget section.\nMan: Great. Can we meet tomorrow to discuss them?\nWoman: Sure, how about 10 AM?\n\nQ: 女性は提案書についてどのような意見を述べましたか？",
      optionA: "全体的には良いが予算部分に改善の余地がある",
      optionB: "全て問題なく承認できる",
      optionC: "予算以外の部分に問題がある",
      optionD: "提案書をまだ読んでいない",
      correctAnswer: "A",
      explanation: "女性は \"Overall it looks good, but I have a few suggestions for the budget section\" と述べており、全体的には良いが予算部分に提案があることを示しています。",
      difficulty: "medium",
      language: "ja",
    },
    {
      subject: "toeic600",
      topic: "リスニング",
      content: "【リスニング練習問題】次の電話メッセージを読んで質問に答えてください。\n\n\"Hi, this is Dr. Smith's office calling to confirm your appointment on Thursday, March 15th at 2:00 PM. If you need to cancel or reschedule, please call us at 555-1234 at least 24 hours before your appointment.\"\n\nQ: キャンセルや予約変更をする場合、何をする必要がありますか？",
      optionA: "24時間前までに555-1234に電話する",
      optionB: "48時間前までに電話する",
      optionC: "オフィスに直接行く",
      optionD: "メールで連絡する",
      correctAnswer: "A",
      explanation: "メッセージに \"call us at 555-1234 at least 24 hours before\" と明記されています。",
      difficulty: "easy",
      language: "ja",
    },
  ];

  // ============================================================
  // TOEIC 800点
  // ============================================================
  const toeic800Questions = [
    // Section A: 高度な語彙・文法
    {
      subject: "toeic800",
      topic: "高度な語彙・文法",
      content: "空欄に入る最も適切な語を選んでください。\n\nThe board of directors has decided to ______ the merger proposal after careful consideration.",
      optionA: "ratify",
      optionB: "rectify",
      optionC: "reiterate",
      optionD: "reimburse",
      correctAnswer: "A",
      explanation: "ratify は「（条約・提案などを）批准する/承認する」という意味です。rectify（修正する）、reiterate（繰り返す）、reimburse（払い戻す）はいずれも文脈に合いません。",
      difficulty: "hard",
      language: "ja",
    },
    {
      subject: "toeic800",
      topic: "高度な語彙・文法",
      content: "空欄に入る最も適切な語を選んでください。\n\n______ the increase in raw material costs, the company managed to maintain its profit margins.",
      optionA: "Despite",
      optionB: "Because of",
      optionC: "Due to",
      optionD: "Owing to",
      correctAnswer: "A",
      explanation: "後半「利益率を維持した」は予想に反する良い結果です。逆接の前置詞 despite（〜にもかかわらず）が正解。because of / due to / owing to はいずれも理由を表し文意に合いません。",
      difficulty: "medium",
      language: "ja",
    },
    {
      subject: "toeic800",
      topic: "高度な語彙・文法",
      content: "空欄に入る最も適切な語を選んでください。\n\nThe new policy requires that every expense report ______ submitted with original receipts.",
      optionA: "be",
      optionB: "is",
      optionC: "was",
      optionD: "will be",
      correctAnswer: "A",
      explanation: "require that節では仮定法現在（動詞の原形）を使います。正しくは \"that every expense report be submitted\" です。これは米語で頻出の仮定法現在です。",
      difficulty: "hard",
      language: "ja",
    },
    {
      subject: "toeic800",
      topic: "高度な語彙・文法",
      content: "次の文中の下線部の意味として最も適切なものを選んでください。\n\nThe CEO's __candid__ remarks surprised many investors at the annual meeting.",
      optionA: "率直な",
      optionB: "準備された",
      optionC: "曖昧な",
      optionD: "批判的な",
      correctAnswer: "A",
      explanation: "candid は「率直な、包み隠さない」という意味の形容詞です。TOEIC上級レベルの頻出語彙です。",
      difficulty: "medium",
      language: "ja",
    },
    {
      subject: "toeic800",
      topic: "高度な語彙・文法",
      content: "空欄に入る最も適切な語を選んでください。\n\nThe marketing team is responsible for ______ customer feedback into actionable strategies.",
      optionA: "translating",
      optionB: "transferring",
      optionC: "transforming",
      optionD: "transmitting",
      correctAnswer: "A",
      explanation: "\"translate A into B\" で「AをBに変換/転換する」という意味です。「顧客フィードバックを実行可能な戦略に変換する」という文脈に最適です。",
      difficulty: "hard",
      language: "ja",
    },
    {
      subject: "toeic800",
      topic: "高度な語彙・文法",
      content: "空欄に入る最も適切な語を選んでください。\n\nThe proposal was well-received by all ______ parties involved in the negotiation.",
      optionA: "stakeholder",
      optionB: "concerned",
      optionC: "interested",
      optionD: "relevant",
      correctAnswer: "D",
      explanation: "\"relevant parties\" は「関係する当事者」という意味で最も自然な表現です。ただし concerned parties / interested parties も文法的には正しいですが、この文脈では relevant が最も適切です。",
      difficulty: "hard",
      language: "ja",
    },
    // Section B: 長文読解
    {
      subject: "toeic800",
      topic: "長文読解",
      content: "次の文書を読んで質問に答えてください。\n\nGreenTech Industries announced today that it will invest $50 million in expanding its solar panel manufacturing facility in Ohio. The expansion will create approximately 500 new jobs and increase production capacity by 40%. CEO Jane Chen stated, \"This investment reflects our commitment to sustainable energy and the growing demand for renewable energy solutions.\" The project is expected to be completed by Q3 of next year.\n\nQ: GreenTechが今回の投資を決定した主な理由として述べられているものはどれか？",
      optionA: "持続可能エネルギーへの取り組みと再生可能エネルギーへの需要増加",
      optionB: "オハイオ州政府からの補助金獲得",
      optionC: "競合他社に対抗するため",
      optionD: "工場の老朽化による設備更新",
      correctAnswer: "A",
      explanation: "CEOの発言 \"commitment to sustainable energy and the growing demand for renewable energy solutions\" から、持続可能エネルギーへの取り組みと需要増加が理由として述べられています。",
      difficulty: "medium",
      language: "ja",
    },
    {
      subject: "toeic800",
      topic: "長文読解",
      content: "次の文書を読んで質問に答えてください。\n\nTo: All Department Heads\nRe: Q4 Budget Submissions\n\nAll departments are required to submit their Q4 budget proposals by October 15th. Proposals should include detailed breakdowns of anticipated expenditures, projected revenues where applicable, and justification for any increase exceeding 10% from Q3 actuals. Finance will schedule individual review meetings the following week.\n\nQ: 10%超の増額を申請する場合、何が必要ですか？",
      optionA: "増額の正当化（justification）",
      optionB: "上司の署名",
      optionC: "過去3年分の実績データ",
      optionD: "外部監査報告書",
      correctAnswer: "A",
      explanation: "メモに \"justification for any increase exceeding 10% from Q3 actuals\" と明記されています。10%超の増加には根拠・正当化が必要です。",
      difficulty: "medium",
      language: "ja",
    },
    {
      subject: "toeic800",
      topic: "長文読解",
      content: "次の文書を読んで質問に答えてください。\n\nMarket Analysis: The global e-commerce sector grew by 18% last year, driven primarily by mobile shopping and same-day delivery services. While traditional retail saw a 3% decline, companies that successfully integrated online and offline channels (omnichannel) reported a 25% increase in customer retention. Analysts predict continued growth of 15% annually over the next five years.\n\nQ: オムニチャネル戦略を採用した企業の顧客維持率はどのくらい向上しましたか？",
      optionA: "25%",
      optionB: "18%",
      optionC: "15%",
      optionD: "3%",
      correctAnswer: "A",
      explanation: "\"companies that successfully integrated online and offline channels (omnichannel) reported a 25% increase in customer retention\" から25%の向上が読み取れます。",
      difficulty: "easy",
      language: "ja",
    },
    {
      subject: "toeic800",
      topic: "長文読解",
      content: "次の文書を読んで質問に答えてください。\n\nWe are pleased to announce that Apex Solutions and DataCore Systems have entered into a strategic partnership. Under this agreement, DataCore will provide its cloud-based analytics platform to Apex's 10,000+ enterprise clients. Revenue sharing will follow a 60/40 split favoring Apex. The partnership is initially set for three years with renewal options.\n\nQ: 収益分配の割合として正しいものはどれか？",
      optionA: "Apexが60%、DataCoreが40%",
      optionB: "DataCoreが60%、Apexが40%",
      optionC: "均等に50/50",
      optionD: "最初の1年は70/30",
      correctAnswer: "A",
      explanation: "\"Revenue sharing will follow a 60/40 split favoring Apex\" から、Apexが有利な60/40分配であることがわかります。",
      difficulty: "medium",
      language: "ja",
    },
    {
      subject: "toeic800",
      topic: "長文読解",
      content: "次のメールを読んで質問に答えてください。\n\nSubject: Contract Renewal – Action Required\n\nDear Ms. Park,\nYour current service contract (# SVC-4892) expires on November 30. To ensure uninterrupted service, please complete the renewal form attached and return it by November 10. If we do not receive your response by that date, your service will be automatically discontinued. Should you have questions regarding upgraded packages, our sales team is available at extension 204.\n\nQ: 返答がなかった場合、どうなりますか？",
      optionA: "11月30日にサービスが自動的に停止される",
      optionB: "サービスが自動更新される",
      optionC: "営業チームから連絡が来る",
      optionD: "追加料金が請求される",
      correctAnswer: "A",
      explanation: "\"your service will be automatically discontinued\" と記載されており、返答がない場合はサービスが停止（11月30日の契約満了時）されます。",
      difficulty: "medium",
      language: "ja",
    },
    // Section C: ビジネスリスニング
    {
      subject: "toeic800",
      topic: "ビジネスリスニング",
      content: "【ビジネスリスニング練習】次の会議の一部を読んで質問に答えてください。\n\nManager: \"I'd like to get everyone's thoughts on the proposed expansion into the Southeast Asian market. Sarah, can you start?\"\nSarah: \"Based on our market research, there's strong demand, but we need to be cautious about regulatory hurdles in some countries.\"\nManager: \"Good point. Tom, what about our financial readiness?\"\nTom: \"Our current cash reserves are sufficient, but we should consider phased investment to minimize risk.\"\n\nQ: トムの財務に関する提案はどれか？",
      optionA: "リスクを最小化するために段階的な投資を検討すべき",
      optionB: "現在の現金準備が不十分だ",
      optionC: "すぐに全額を投資すべき",
      optionD: "外部資金調達が必要だ",
      correctAnswer: "A",
      explanation: "トムは \"phased investment to minimize risk\" (リスクを最小化するための段階的投資) を提案しています。",
      difficulty: "medium",
      language: "ja",
    },
    {
      subject: "toeic800",
      topic: "ビジネスリスニング",
      content: "【ビジネスリスニング練習】次のプレゼンテーションの一部を読んで質問に答えてください。\n\n\"Good morning, everyone. Today I'll be presenting our Q3 results. Overall, we exceeded our targets by 12%, primarily driven by strong performance in the Asia-Pacific region. However, our European operations underperformed by 8% due to supply chain disruptions. Looking ahead, we're implementing new logistics partnerships to address this issue.\"\n\nQ: ヨーロッパでの業績不振の原因として述べられているものはどれか？",
      optionA: "サプライチェーンの混乱",
      optionB: "需要の低下",
      optionC: "競合他社の台頭",
      optionD: "コスト増加",
      correctAnswer: "A",
      explanation: "プレゼンで \"European operations underperformed by 8% due to supply chain disruptions\" と明確に述べられています。",
      difficulty: "medium",
      language: "ja",
    },
    {
      subject: "toeic800",
      topic: "ビジネスリスニング",
      content: "【ビジネスリスニング練習】次の電話会話を読んで質問に答えてください。\n\nCaller: \"Hello, I'm calling about invoice #7891. It appears there's a discrepancy between the amount billed and what we agreed upon in our contract.\"\nReceptionist: \"I apologize for the inconvenience. Let me transfer you to our accounts receivable department. They'll be able to resolve this promptly.\"\nCaller: \"Thank you. Also, could you make sure to note that this needs to be resolved before the payment due date on the 25th?\"\n\nQ: 発信者の主な問題は何ですか？",
      optionA: "請求書の金額と契約内容に相違がある",
      optionB: "請求書が届いていない",
      optionC: "支払期限を過ぎてしまった",
      optionD: "間違った部門に連絡した",
      correctAnswer: "A",
      explanation: "発信者は \"a discrepancy between the amount billed and what we agreed upon in our contract\" (請求額と契約合意額の不一致) を問題として述べています。",
      difficulty: "medium",
      language: "ja",
    },
    {
      subject: "toeic800",
      topic: "ビジネスリスニング",
      content: "【ビジネスリスニング練習】次のビジネスアナウンスを読んで質問に答えてください。\n\n\"Attention all employees: effective from the first of next month, the company will be implementing a new flexible work-from-home policy. Employees may work remotely up to three days per week, subject to manager approval. All remote work must be conducted during core hours of 9 AM to 3 PM. Details will be distributed via email by HR within the week.\"\n\nQ: 新しいリモートワークポリシーについて正しいものはどれか？",
      optionA: "週最大3日間、上司の承認のもとでリモートワーク可能",
      optionB: "全員が毎日リモートワークできる",
      optionC: "リモートワークの時間帯に制限はない",
      optionD: "承認不要でリモートワークできる",
      correctAnswer: "A",
      explanation: "\"up to three days per week\" (週最大3日) と \"subject to manager approval\" (上司の承認が必要) が正確に述べられています。",
      difficulty: "medium",
      language: "ja",
    },
  ];

  // Insert all questions
  const allQuestions = [
    ...bookkeeping3Questions,
    ...bookkeeping2Questions,
    ...toeic600Questions,
    ...toeic800Questions,
  ];

  for (const q of allQuestions) {
    await prisma.question.create({ data: q });
  }

  console.log(`Seeded ${bookkeeping3Questions.length} bookkeeping3 questions`);
  console.log(`Seeded ${bookkeeping2Questions.length} bookkeeping2 questions`);
  console.log(`Seeded ${toeic600Questions.length} toeic600 questions`);
  console.log(`Seeded ${toeic800Questions.length} toeic800 questions`);
  console.log("Done!");
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
